# Generated by Django 6.0.3 on 2026-04-06 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0008_remove_productsegment_sub_group_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'raw_material_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='raw_materials_stock.location')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='master_data.rawmaterialandconsumable')),
            ],
            options={
                'db_table': 'raw_material_stock',
                'ordering': ['material__name', 'location__name'],
                'unique_together': {('material', 'location')},
            },
        ),
        migrations.CreateModel(
            name='RawMaterialStockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase / Receipt'), ('return', 'Return from Production'), ('transfer_in', 'Transfer In'), ('usage', 'Usage in Production'), ('wastage', 'Wastage / Damage'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Stock Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost per unit at time of movement (for purchase/usage costing).', max_digits=14, null=True)),
                ('reference', models.CharField(blank=True, help_text='PO number, production order ID, transfer slip, etc.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterpart_location', models.ForeignKey(blank=True, help_text='Destination (for transfer_out) or source (for transfer_in).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterpart_stock_logs', to='raw_materials_stock.location')),
                ('location', models.ForeignKey(help_text='Primary location affected by this movement.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='raw_materials_stock.location')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='master_data.rawmaterialandconsumable')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'raw_material_stock_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['material', 'location', '-created_at'], name='raw_materia_materia_126469_idx'), models.Index(fields=['movement_type'], name='raw_materia_movemen_7b98a5_idx'), models.Index(fields=['reference'], name='raw_materia_referen_e67905_idx')],
            },
        ),
    ]
