# Generated by Django 6.0.3 on 2026-04-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_remove_productsegment_sub_group_product'),
        ('raw_materials_stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rawmaterialstocklog',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='raw_materials_stock.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='short_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('zone', 'Zone'), ('block', 'Block'), ('aisle', 'Aisle'), ('rack', 'Rack'), ('shelf', 'Shelf')], default='warehouse', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rawmaterialstocklog',
            name='location',
            field=models.ForeignKey(help_text='Primary location affected by this movement.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='master_data.location'),
        ),
    ]
