# Generated by Django 6.0.3 on 2026-04-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials_stock', '0002_remove_location_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialstocklog',
            name='location',
            field=models.ForeignKey(help_text='Primary location affected by this movement.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='raw_materials_stock.location'),
        ),
    ]
