# Generated by Django 6.0.3 on 2026-04-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_remove_productsegment_sub_group_product'),
        ('raw_materials_stock', '0003_alter_rawmaterialstocklog_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialstocklog',
            name='location',
            field=models.ForeignKey(help_text='Primary location affected by this movement.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='master_data.location'),
        ),
        migrations.AlterField(
            model_name='rawmaterialstocklog',
            name='counterpart_location',
            field=models.ForeignKey(blank=True, help_text='Destination (for transfer_out) or source (for transfer_in).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterpart_stock_logs', to='master_data.location'),
        ),
        migrations.AlterField(
            model_name='rawmaterialstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='master_data.location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
