# Generated by Django 6.0.3 on 2026-04-19 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_delete_productbatch'),
        ('raw_materials_stock', '0004_alter_rawmaterialstocklog_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.location'),
        ),
        migrations.AlterField(
            model_name='rawmaterialstock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.rawmaterialandconsumable'),
        ),
        migrations.CreateModel(
            name='RawMaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='master_data.rawmaterialandconsumable')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.supplier')),
            ],
            options={
                'db_table': 'raw_material_batches',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rawmaterialstock',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='raw_materials_stock.rawmaterialbatch'),
        ),
        migrations.AddField(
            model_name='rawmaterialstocklog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='raw_materials_stock.rawmaterialbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialstock',
            unique_together={('material', 'location', 'batch')},
        ),
    ]
