# Generated by Django 6.0.3 on 2026-04-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0001_initial'),
        ('master_data', '0012_delete_productbatch'),
        ('raw_materials_stock', '0005_alter_rawmaterialstock_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialstocklog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='inventory_core.batch'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialstock',
            unique_together={('material', 'location')},
        ),
        migrations.RemoveField(
            model_name='rawmaterialstock',
            name='batch',
        ),
        migrations.DeleteModel(
            name='RawMaterialBatch',
        ),
    ]
