# Generated by Django 6.0.3 on 2026-04-20 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_delete_productbatch'),
        ('raw_materials_stock', '0007_alter_rawmaterialstock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialstocklog',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_stock_logs', to='master_data.supplier'),
        ),
    ]
