# Generated by Django 6.0.3 on 2026-04-26 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0002_lpn'),
        ('master_data', '0012_delete_productbatch'),
        ('raw_materials_stock', '0008_rawmaterialstocklog_supplier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawmaterialstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rawmaterialstock',
            name='lpn',
            field=models.ForeignKey(blank=True, help_text='The physical License Plate Number containing this stock (e.g. split roll, pallet).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_stock_levels', to='inventory_core.lpn'),
        ),
        migrations.AddField(
            model_name='rawmaterialstocklog',
            name='lpn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_stock_logs', to='inventory_core.lpn'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialstock',
            unique_together={('material', 'location', 'batch', 'lpn')},
        ),
    ]
