# Generated by Django 6.0.3 on 2026-04-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials_stock', '0009_alter_rawmaterialstock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialstocklog',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase / Receipt'), ('return', 'Return from Production'), ('transfer_in', 'Transfer In'), ('adjustment_in', 'Adjustment (In)'), ('usage', 'Usage in Production'), ('wastage', 'Wastage / Damage'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment (Out)')], max_length=20),
        ),
    ]
