# Generated by Django 6.0.3 on 2026-06-28 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0038_backfill_variant_sku_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('assembly_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_consumable_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consumable_requests', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_requests_destination', to='master_data.location')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_consumable_requests', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_consumable_requests', to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_requests_source', to='master_data.location')),
            ],
            options={
                'db_table': 'consumable_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('approved_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('dispatched_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('used_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('returned_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_request_items', to='master_data.rawmaterialandconsumable')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consumables.consumablerequest')),
            ],
            options={
                'db_table': 'consumable_request_items',
            },
        ),
    ]
