# Generated by Django 6.0.3 on 2026-06-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('returned', 'Returned'), ('consumed', 'Consumed')], default='draft', max_length=20),
        ),
    ]
