# Generated by Django 6.0.3 on 2026-06-30 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0002_alter_consumablerequest_status'),
        ('master_data', '0038_backfill_variant_sku_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablerequest',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_requests_source', to='master_data.location'),
        ),
    ]
