# Generated by Django 6.0.3 on 2026-05-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_alter_location_code'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('produced_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kettle', models.ForeignKey(help_text='The Machine/Location (e.g. Kettle) where this order is produced.', on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='master_data.location')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.recipe')),
            ],
            options={
                'db_table': 'production_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('actual_consumed_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('wastage_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.rawmaterialandconsumable')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.productionorder')),
            ],
            options={
                'db_table': 'production_order_materials',
                'unique_together': {('order', 'material')},
            },
        ),
    ]
