# Generated by Django 6.0.3 on 2026-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionorder_productionordermaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='expected_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
