# Generated by Django 6.0.3 on 2026-05-25 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0003_lpncounter'),
        ('production', '0005_productionorder_mixing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorycontainercode',
            name='location',
        ),
        migrations.RemoveField(
            model_name='factorycontainercode',
            name='material',
        ),
        migrations.RemoveField(
            model_name='factorycontainercode',
            name='parent_fcc',
        ),
        migrations.RemoveField(
            model_name='factorycontainercode',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='fccmovement',
            name='fcc',
        ),
        migrations.DeleteModel(
            name='FCCCounter',
        ),
        migrations.RemoveField(
            model_name='fccmovement',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='fccmovement',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='fccmovement',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='fccmovement',
            name='to_location',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='produced_batch',
            field=models.ForeignKey(blank=True, help_text='Auto-generated PRD batch for the finished product on order completion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='inventory_core.batch'),
        ),
        migrations.DeleteModel(
            name='FactoryContainerCode',
        ),
        migrations.DeleteModel(
            name='FCCMovement',
        ),
    ]
