# Generated by Django 6.0.3 on 2026-05-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_productionorder_produced_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='materials_confirmed',
            field=models.BooleanField(default=False, help_text='Set to True once operator has verified all materials are loaded in the kettle.'),
        ),
    ]
