# Generated by Django 6.0.3 on 2026-05-26 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_materials_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='mixture_id',
            field=models.CharField(blank=True, help_text='Auto-generated ID for orders created without a recipe (custom mix).', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.recipe'),
        ),
    ]
