# Generated by Django 6.0.3 on 2026-05-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_optional_recipe_mixture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionordermaterial',
            name='is_loaded',
            field=models.BooleanField(default=False, help_text='Operator confirms material has been physically loaded into the kettle.'),
        ),
    ]
