# Generated by Django 6.0.3 on 2026-05-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_ordermaterial_is_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionordermaterial',
            name='actual_load_qty',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Actual quantity loaded by operator; may differ from planned. Used for consumption.', max_digits=14, null=True),
        ),
    ]
