# Generated by Django 6.0.3 on 2026-06-07 09:55

import production.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_ordermaterial_actual_load_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='encrypted_material_name',
            field=production.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=production.encryption.EncryptedDecimalField(),
        ),
    ]
