# Generated by Django 6.0.3 on 2026-06-24 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0008_remove_palletitem_unique_pallet_lpn_and_more'),
        ('production', '0013_fix_double_encrypted_recipe_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstFillTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'Testing'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=20, null=True)),
                ('sample_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('date_of_sample_receipt', models.DateField(blank=True, null=True)),
                ('date_of_analysis', models.DateField(blank=True, null=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_fill_tests', to='inventory_core.batch')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_fill_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_first_fill_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirstFillTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField()),
                ('characteristic', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('test_method', models.CharField(blank=True, max_length=100)),
                ('specification', models.CharField(blank=True, max_length=200)),
                ('spec_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('spec_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('result_value', models.CharField(blank=True, max_length=200)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='production.firstfilltest')),
            ],
            options={
                'db_table': 'production_first_fill_test_results',
                'ordering': ['sr_no'],
            },
        ),
    ]
