# Generated by Django 6.0.3 on 2026-06-24 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0037_parameter_testdefinition_product_default_test_and_more'),
        ('production', '0014_firstfilltest_firstfilltestresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstfilltest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='firstfilltest',
            name='result',
        ),
        migrations.RemoveField(
            model_name='firstfilltest',
            name='sample_quantity',
        ),
        migrations.RemoveField(
            model_name='firstfilltest',
            name='tested_by',
        ),
        migrations.RemoveField(
            model_name='firstfilltestresult',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='firstfilltestresult',
            name='result_value',
        ),
        migrations.RemoveField(
            model_name='firstfilltestresult',
            name='spec_max',
        ),
        migrations.RemoveField(
            model_name='firstfilltestresult',
            name='spec_min',
        ),
        migrations.RemoveField(
            model_name='firstfilltestresult',
            name='specification',
        ),
        migrations.AddField(
            model_name='firstfilltest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_fill_tests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firstfilltest',
            name='batch_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='firstfilltest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_fill_tests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firstfilltest',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firstfilltest',
            name='overall_verdict',
            field=models.CharField(choices=[('pending', 'Pending'), ('conforms', 'Conforms'), ('non_conforming', 'Non-conforming')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='firstfilltest',
            name='quantity_unit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firstfilltest',
            name='test_definition',
            field=models.ForeignKey(blank=True, help_text='Report format used for this batch (e.g. Engine Oil COA). Always set by start().', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='master_data.testdefinition'),
        ),
        migrations.AddField(
            model_name='firstfilltestresult',
            name='entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firstfilltestresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firstfilltestresult',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firstfilltestresult',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='firstfilltestresult',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='firstfilltestresult',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.parameter'),
        ),
        migrations.AddField(
            model_name='firstfilltestresult',
            name='result_numeric',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='firstfilltestresult',
            name='result_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='firstfilltestresult',
            name='spec_type',
            field=models.CharField(choices=[('Report', 'Report'), ('Min', 'Min'), ('Max', 'Max'), ('Range', 'Range')], default='Report', max_length=10),
        ),
        migrations.AddField(
            model_name='firstfilltestresult',
            name='verdict',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'N/A')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='firstfilltest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('issued', 'Issued')], default='draft', max_length=20),
        ),
    ]
