# Generated by Django 6.0.3 on 2026-06-10 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_core', '0005_batch_finished_product_variant'),
        ('master_data', '0030_make_finished_product_name_optional'),
        ('sales', '0003_add_retail_customer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('packing', 'Packing'), ('rechecked', 'Rechecked'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('dealer_notes', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatches', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='sales.customer')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_orders', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='sales.invoice')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_dispatches', to=settings.AUTH_USER_MODEL)),
                ('rechecked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechecked_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispatch_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('packed_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('rechecked_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='inventory_core.batch')),
                ('finished_product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='master_data.finishedproductvariant')),
                ('lpn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='inventory_core.lpn')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='master_data.location')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispatch.dispatchorder')),
            ],
            options={
                'db_table': 'dispatch_items',
            },
        ),
        migrations.CreateModel(
            name='DealerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_stock', to='inventory_core.batch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealer_stock', to='sales.customer')),
                ('finished_product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealer_stock', to='master_data.finishedproductvariant')),
            ],
            options={
                'db_table': 'dealer_stock',
                'ordering': ['customer', 'finished_product_variant'],
                'unique_together': {('customer', 'finished_product_variant', 'batch')},
            },
        ),
    ]
