# Generated by Django 6.0.3 on 2026-05-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_base32_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
