# Generated by Django 6.0.3 on 2026-04-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0012_delete_productbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('batch_type', models.CharField(choices=[('RAW', 'Raw Material'), ('PRD', 'Product')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='master_data.product')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='master_data.rawmaterialandconsumable')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.supplier')),
            ],
            options={
                'db_table': 'inventory_batches',
            },
        ),
        migrations.CreateModel(
            name='BatchCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('batch_type', models.CharField(max_length=10)),
                ('letter', models.CharField(default='A', max_length=1)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'batch_type', 'letter')},
            },
        ),
    ]
