# Generated by Django 6.0.3 on 2026-04-26 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpn_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lpns', to='inventory_core.batch')),
                ('parent_lpn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_lpns', to='inventory_core.lpn')),
            ],
            options={
                'verbose_name_plural': 'LPNs',
                'db_table': 'inventory_lpns',
            },
        ),
    ]
