# Generated by Django 6.0.3 on 2026-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0002_lpn'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPNCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='L', max_length=2)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory_lpn_counter',
            },
        ),
    ]
