# Generated by Django 6.0.3 on 2026-05-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0003_lpncounter'),
        ('master_data', '0021_remove_product_capacity_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='finished_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='master_data.finishedproduct'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('PRD', 'Product'), ('FIN', 'Finished Product')], max_length=10),
        ),
    ]
