# Generated by Django 6.0.3 on 2026-05-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0004_batch_finished_product_alter_batch_batch_type'),
        ('master_data', '0025_data_migrate_fp_to_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='finished_product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='master_data.finishedproductvariant'),
        ),
    ]
