# Generated by Django 6.0.3 on 2026-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0007_palletitem_switch_to_lpn'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='palletitem',
            name='unique_pallet_lpn',
        ),
        migrations.AddField(
            model_name='batch',
            name='quality_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Test'), ('passed', 'Passed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='not_required', help_text='First Fill Test gate for PRD batches before they can be picked into Assembly.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='palletitem',
            unique_together={('pallet', 'lpn')},
        ),
    ]
