# Generated by Django 6.0.3 on 2026-06-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0008_remove_palletitem_unique_pallet_lpn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('RAW', 'Raw Materials'), ('PRD', 'Production Goods'), ('FIN', 'Finished Goods')], max_length=10),
        ),
    ]
