# Generated by Django 6.0.3 on 2026-06-09 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '0007_add_label_print_job'),
        ('inventory_core', '0005_batch_finished_product_variant'),
        ('master_data', '0030_make_finished_product_name_optional'),
        ('production', '0013_fix_double_encrypted_recipe_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_number', models.CharField(max_length=50, unique=True)),
                ('mode', models.CharField(choices=[('direct', 'Direct Repack'), ('via_assembly', 'Via Assembly'), ('via_kettle_and_assembly', 'Via Kettle & Assembly')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_kettle', 'Awaiting Kettle Completion'), ('awaiting_assembly', 'Awaiting Assembly Completion'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('source_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('output_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_orders_destination', to='master_data.location')),
                ('destination_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_orders_as_destination', to='master_data.finishedproductvariant')),
                ('linked_assembly_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refill_order', to='assembly.assemblyorder')),
                ('linked_production_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refill_order', to='production.productionorder')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refill_orders', to=settings.AUTH_USER_MODEL)),
                ('recovery_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refill_orders_as_recovery', to='inventory_core.batch')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_orders_as_source', to='inventory_core.batch')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_orders_source', to='master_data.location')),
                ('source_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_orders_as_source', to='master_data.finishedproductvariant')),
            ],
            options={
                'db_table': 'refill_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
