# Generated by Django 6.0.3 on 2026-06-09 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0030_make_finished_product_name_optional'),
        ('refill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refillorder',
            name='assembly_location',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'assembly'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refill_orders_assembly', to='master_data.location'),
        ),
    ]
