# Generated by Django 6.0.3 on 2026-05-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_core', '0004_batch_finished_product_alter_batch_batch_type'),
        ('master_data', '0021_remove_product_capacity_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('produced_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('sticker_confirmed', models.BooleanField(default=False)),
                ('operator_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_dest_orders', to='master_data.location')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_orders', to='master_data.finishedproduct')),
                ('produced_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_orders', to='inventory_core.batch')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packaging_source', to='inventory_core.batch')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_source_orders', to='master_data.location')),
            ],
            options={
                'db_table': 'packaging_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
