# Generated by Django 6.0.3 on 2026-05-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0025_data_migrate_fp_to_variants'),
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagingorder',
            name='finished_product',
        ),
        migrations.AddField(
            model_name='packagingorder',
            name='finished_product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packaging_orders', to='master_data.finishedproductvariant'),
        ),
    ]
