# Generated by Django 6.0.3 on 2026-05-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0004_packagingorder_redesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagingorder',
            name='target_quantity',
        ),
    ]
