# Generated by Django 6.0.3 on 2026-04-20 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0001_initial'),
        ('products_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_stock_levels', to='inventory_core.batch'),
        ),
    ]
