# Generated by Django 6.0.3 on 2026-04-20 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_delete_productbatch'),
        ('products_stock', '0002_alter_productstock_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocklog',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_stock_logs', to='master_data.supplier'),
        ),
    ]
