# Generated by Django 6.0.3 on 2026-04-26 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0002_lpn'),
        ('master_data', '0012_delete_productbatch'),
        ('products_stock', '0003_productstocklog_supplier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productstock',
            name='lpn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_stock_levels', to='inventory_core.lpn'),
        ),
        migrations.AddField(
            model_name='productstocklog',
            name='lpn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_core.lpn'),
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'batch', 'location', 'lpn')},
        ),
    ]
