# Generated by Django 6.0.3 on 2026-04-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_stock', '0004_alter_productstock_unique_together_productstock_lpn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstocklog',
            name='movement_type',
            field=models.CharField(choices=[('production', 'Production'), ('sale', 'Sale / Issue'), ('sale_return', 'Customer Return'), ('purchase', 'Purchase / Receipt'), ('purchase_return', 'Return to Supplier'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment (Out)'), ('adjustment_in', 'Adjustment (In)'), ('wastage', 'Wastage')], max_length=20),
        ),
    ]
