# Generated by Django 6.0.3 on 2026-05-27 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0004_batch_finished_product_alter_batch_batch_type'),
        ('master_data', '0021_remove_product_capacity_value_and_more'),
        ('products_stock', '0005_alter_productstocklog_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstocklog',
            name='movement_type',
            field=models.CharField(choices=[('production', 'Production'), ('packaging_usage', 'Packaging Usage'), ('sale', 'Sale / Issue'), ('sale_return', 'Customer Return'), ('purchase', 'Purchase / Receipt'), ('purchase_return', 'Return to Supplier'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment (Out)'), ('adjustment_in', 'Adjustment (In)'), ('wastage', 'Wastage')], max_length=20),
        ),
        migrations.CreateModel(
            name='FinishedProductStockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('packaging_production', 'Packaging Production'), ('sale', 'Sale / Issue'), ('sale_return', 'Customer Return'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment (Out)'), ('adjustment_in', 'Adjustment (In)'), ('wastage', 'Wastage')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_core.batch')),
                ('counterpart_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_product_counterpart_logs', to='master_data.location')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_logs', to='master_data.finishedproduct')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.location')),
                ('lpn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_core.lpn')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finished_product_stock_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinishedProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_product_stock_levels', to='inventory_core.batch')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='master_data.finishedproduct')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.location')),
                ('lpn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_product_stock_levels', to='inventory_core.lpn')),
            ],
            options={
                'verbose_name_plural': 'Finished Product Stocks',
                'db_table': 'finished_product_stock',
                'unique_together': {('finished_product', 'batch', 'location', 'lpn')},
            },
        ),
    ]
