# Generated by Django 6.0.3 on 2026-05-27 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0004_batch_finished_product_alter_batch_batch_type'),
        ('master_data', '0021_remove_product_capacity_value_and_more'),
        ('products_stock', '0006_alter_productstocklog_movement_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishedproductstock',
            options={'ordering': ['finished_product__name', 'location__name'], 'verbose_name_plural': 'Finished Product Stocks'},
        ),
        migrations.AddField(
            model_name='finishedproductstocklog',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_product_stock_logs', to='master_data.supplier'),
        ),
        migrations.AlterField(
            model_name='finishedproductstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_product_stock_levels', to='master_data.location'),
        ),
        migrations.AlterField(
            model_name='finishedproductstocklog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_product_stock_logs', to='inventory_core.batch'),
        ),
        migrations.AlterField(
            model_name='finishedproductstocklog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_product_stock_logs', to='master_data.location'),
        ),
        migrations.AlterField(
            model_name='finishedproductstocklog',
            name='lpn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_product_stock_logs', to='inventory_core.lpn'),
        ),
        migrations.AlterField(
            model_name='finishedproductstocklog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_product_stock_log_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='finishedproductstocklog',
            index=models.Index(fields=['finished_product', 'location', '-created_at'], name='finished_pr_finishe_3295af_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedproductstocklog',
            index=models.Index(fields=['movement_type'], name='finished_pr_movemen_e14efc_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedproductstocklog',
            index=models.Index(fields=['reference'], name='finished_pr_referen_ccdd93_idx'),
        ),
    ]
