# Generated by Django 6.0.3 on 2026-05-28 09:55 (operation order fixed manually)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0005_batch_finished_product_variant'),
        ('master_data', '0025_data_migrate_fp_to_variants'),
        ('products_stock', '0007_alter_finishedproductstock_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Remove old unique_together that references finished_product
        migrations.AlterUniqueTogether(
            name='finishedproductstock',
            unique_together=set(),
        ),
        # Step 2: Remove old index referencing finished_product
        migrations.RemoveIndex(
            model_name='finishedproductstocklog',
            name='finished_pr_finishe_3295af_idx',
        ),
        # Step 3: Remove old finished_product FK fields
        migrations.RemoveField(
            model_name='finishedproductstocklog',
            name='finished_product',
        ),
        migrations.RemoveField(
            model_name='finishedproductstock',
            name='finished_product',
        ),
        # Step 4: Add new finished_product_variant FK fields
        migrations.AddField(
            model_name='finishedproductstock',
            name='finished_product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='master_data.finishedproductvariant'),
        ),
        migrations.AddField(
            model_name='finishedproductstocklog',
            name='finished_product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_logs', to='master_data.finishedproductvariant'),
        ),
        # Step 5: Update meta options and add new index/unique_together
        migrations.AlterModelOptions(
            name='finishedproductstock',
            options={'ordering': ['finished_product_variant__finished_product__name', 'location__name'], 'verbose_name_plural': 'Finished Product Stocks'},
        ),
        migrations.AlterUniqueTogether(
            name='finishedproductstock',
            unique_together={('finished_product_variant', 'batch', 'location', 'lpn')},
        ),
        migrations.AddIndex(
            model_name='finishedproductstocklog',
            index=models.Index(fields=['finished_product_variant', 'location', '-created_at'], name='finished_pr_finishe_52626e_idx'),
        ),
    ]
