# Generated by Django 6.0.3 on 2026-06-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_stock', '0008_alter_finishedproductstock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproductstocklog',
            name='movement_type',
            field=models.CharField(choices=[('packaging_production', 'Packaging Production'), ('purchase', 'Purchase / Receipt'), ('purchase_return', 'Return to Supplier'), ('sale', 'Sale / Issue'), ('sale_return', 'Customer Return'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment (Out)'), ('adjustment_in', 'Adjustment (In)'), ('wastage', 'Wastage')], max_length=30),
        ),
    ]
