# Generated by Django 6.0.3 on 2026-06-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_stock', '0009_add_purchase_to_fp_movement_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproductstocklog',
            name='movement_type',
            field=models.CharField(choices=[('packaging_production', 'Packaging Production'), ('purchase', 'Purchase / Receipt'), ('purchase_return', 'Return to Supplier'), ('sale', 'Sale / Issue'), ('sale_return', 'Customer Return'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment (Out)'), ('adjustment_in', 'Adjustment (In)'), ('wastage', 'Wastage'), ('refill_in', 'Refill / Repack In'), ('refill_out', 'Refill / Repack Out')], max_length=30),
        ),
        migrations.AlterField(
            model_name='productstocklog',
            name='movement_type',
            field=models.CharField(choices=[('production', 'Production'), ('packaging_usage', 'Packaging Usage'), ('sale', 'Sale / Issue'), ('sale_return', 'Customer Return'), ('purchase', 'Purchase / Receipt'), ('purchase_return', 'Return to Supplier'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment (Out)'), ('adjustment_in', 'Adjustment (In)'), ('wastage', 'Wastage'), ('refill_recovery', 'Refill Recovery (Unpack)')], max_length=20),
        ),
    ]
