# Generated by Django 6.0.3 on 2026-06-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_stock', '0010_alter_finishedproductstocklog_movement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproductstocklog',
            name='movement_type',
            field=models.CharField(choices=[('packaging_production', 'Packaging Production'), ('purchase', 'Purchase / Receipt'), ('purchase_return', 'Return to Supplier'), ('sale', 'Sale / Issue'), ('sale_return', 'Customer Return'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment (Out)'), ('adjustment_in', 'Adjustment (In)'), ('wastage', 'Wastage'), ('refill_in', 'Refill / Repack In'), ('refill_out', 'Refill / Repack Out'), ('dispatch_out', 'Dispatch to Dealer')], max_length=30),
        ),
    ]
