# Generated by Django 6.0.3 on 2026-03-31 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_asset_assetparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_code', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('warehouse', 'Warehouse'), ('zone', 'Zone'), ('block', 'Block'), ('aisle', 'Aisle'), ('rack', 'Rack'), ('shelf', 'Shelf')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='master_data.location')),
            ],
            options={
                'unique_together': {('short_code', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='master_data.location'),
        ),
    ]
