# Generated by Django 6.0.3 on 2026-04-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_alter_asset_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialAndConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('raw_material', 'Raw Material'), ('consumable', 'Consumable')], max_length=20)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_materials_and_consumables', to='master_data.unit')),
            ],
            options={
                'db_table': 'master_raw_materials_and_consumables',
                'ordering': ['name'],
            },
        ),
    ]
