# Generated by Django 6.0.3 on 2026-04-02 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_rawmaterialandconsumable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'master_product_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_groups', to='master_data.productgroup')),
            ],
            options={
                'db_table': 'master_product_sub_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='master_data.productsubgroup')),
            ],
            options={
                'db_table': 'master_product_segments',
                'ordering': ['name'],
            },
        ),
    ]
