# Generated by Django 6.0.3 on 2026-04-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_productgroup_productsubgroup_productsegment'),
    ]

    operations = []
