# Generated by Django 6.0.3 on 2026-04-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_productgroup_productsubgroup_productsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsegment',
            name='sub_group',
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name='segments',
                to='master_data.productsubgroup'
            ),
        ),
    ]
