# Generated by Django 6.0.3 on 2026-04-07 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_remove_productsegment_sub_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsegment',
            name='sub_group',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='master_data.productgroup')),
                ('product_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='master_data.productsegment')),
                ('product_sub_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='master_data.productsubgroup')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='master_data.unit')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
    ]
