# Generated by Django 6.0.3 on 2026-04-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_remove_productsegment_sub_group_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(default='', max_length=8),
        ),
    ]
