# Generated by Django 6.0.3 on 2026-04-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_supplier_alter_assetparameter_value_productbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='notes',
        ),
    ]
