# Generated by Django 6.0.3 on 2026-04-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_remove_supplier_gst_number_remove_supplier_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductBatch',
        ),
    ]
