# Generated by Django 6.0.3 on 2026-05-10 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_delete_productbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_products', to='master_data.unit'),
        ),
        migrations.AddField(
            model_name='rawmaterialandconsumable',
            name='capacity_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialandconsumable',
            name='secondary_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_raw_materials', to='master_data.unit'),
        ),
    ]
