# Generated by Django 6.0.3 on 2026-05-19 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_product_capacity_value_product_secondary_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='capacity_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_capacities', to='master_data.unit'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('building', 'Building'), ('factory', 'Factory'), ('zone', 'Zone'), ('block', 'Block'), ('aisle', 'Aisle'), ('rack', 'Rack'), ('shelf', 'Shelf'), ('tank', 'Tank')], max_length=50),
        ),
    ]
