# Generated by Django 6.0.3 on 2026-05-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_location_capacity_location_capacity_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='linked_asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_location', to='master_data.asset'),
        ),
    ]
