# Generated by Django 6.0.3 on 2026-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_remove_asset_location_location_linked_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
