# Generated by Django 6.0.3 on 2026-05-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_alter_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_production_area',
            field=models.BooleanField(default=False),
        ),
    ]
