# Generated by Django 6.0.3 on 2026-05-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_location_is_production_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='location',
            name='capacity_unit',
        ),
    ]
