# Generated by Django 6.0.3 on 2026-05-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_remove_location_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('mixing', 'Mixing'), ('idle', 'Idle')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('building', 'Building'), ('factory', 'Factory'), ('zone', 'Zone'), ('block', 'Block'), ('aisle', 'Aisle'), ('rack', 'Rack'), ('shelf', 'Shelf'), ('tank', 'Tank'), ('kettle', 'Kettle')], max_length=50),
        ),
    ]
