# Generated by Django 6.0.3 on 2026-05-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_alter_location_type_assembly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='capacity_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondary_unit',
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=10)),
                ('container_type', models.CharField(choices=[('bottle', 'Bottle'), ('can', 'Can'), ('jar', 'Jar'), ('pouch', 'Pouch'), ('box', 'Box'), ('drum', 'Drum'), ('other', 'Other')], max_length=20)),
                ('added_sticker', models.BooleanField(default=False)),
                ('sticker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity_value', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('base_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sku_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_products', to='master_data.product')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_products', to='master_data.productgroup')),
                ('product_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_products', to='master_data.productsegment')),
                ('product_sub_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_products', to='master_data.productsubgroup')),
                ('secondary_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_finished_products', to='master_data.unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_products_unit', to='master_data.unit')),
                ('volume_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_products_volume', to='master_data.unit')),
            ],
            options={
                'db_table': 'finished_products',
                'ordering': ['name'],
            },
        ),
    ]
