# Generated by Django 6.0.3 on 2026-05-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_remove_product_capacity_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_segment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sub_group',
        ),
    ]
