# Generated by Django 6.0.3 on 2026-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_remove_product_category_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20),
        ),
    ]
