# Generated by Django 6.0.3 on 2026-05-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_add_unit_type_to_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='base_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='container_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_products_unit', to='master_data.unit'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='volume_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_products_volume', to='master_data.unit'),
        ),
        migrations.CreateModel(
            name='FinishedProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, choices=[('pet', 'PET Plastic'), ('hdpe', 'HDPE Plastic'), ('glass', 'Glass'), ('metal', 'Metal / Tin'), ('foil', 'Foil / Laminate'), ('paper', 'Paper / Cardboard'), ('other', 'Other')], max_length=20, null=True)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=14)),
                ('capacity_value', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True)),
                ('base_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('sku_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('added_sticker', models.BooleanField(default=False)),
                ('sticker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='master_data.finishedproduct')),
                ('secondary_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fp_variants_secondary', to='master_data.unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fp_variants_unit', to='master_data.unit')),
                ('volume_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fp_variants_volume', to='master_data.unit')),
            ],
            options={
                'db_table': 'finished_product_variants',
                'ordering': ['finished_product__name', 'volume'],
                'unique_together': {('finished_product', 'unit', 'volume', 'volume_unit')},
            },
        ),
    ]
