# Generated by Django 6.0.3 on 2026-05-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0025_data_migrate_fp_to_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproduct',
            name='added_sticker',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='base_quantity',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='capacity_value',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='container_type',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='secondary_unit',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='sku_code',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='sticker_name',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='volume_unit',
        ),
    ]
