# Generated by Django 6.0.3 on 2026-05-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_remove_finished_product_legacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='icon',
            field=models.CharField(blank=True, choices=[('bottle', 'Bottle'), ('can', 'Can / Tin'), ('pail', 'Pail / Bucket'), ('drum', 'Drum / Barrel'), ('pouch', 'Pouch / Bag'), ('box', 'Box / Carton'), ('tube', 'Tube'), ('sachet', 'Sachet / Packet'), ('jug', 'Jug / Jerry Can'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
