# Generated by Django 6.0.3 on 2026-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0027_add_icon_to_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='icon',
            field=models.CharField(blank=True, choices=[('bottle', 'Bottle'), ('can', 'Can / Tin'), ('pail', 'Pail / Bucket'), ('drum', 'Drum / Barrel'), ('pouch', 'Pouch / Bag'), ('box', 'Box / Carton'), ('jug', 'Jug / Jerry Can'), ('jar', 'Jar'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
