# Generated by Django 6.0.3 on 2026-06-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0029_unit_base_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
