# Generated by Django 6.0.3 on 2026-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0030_make_finished_product_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproductvariant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finishedproductvariant',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
