# Generated by Django 6.0.3 on 2026-06-16 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0032_remove_productsubgroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroups', to='master_data.productgroup'),
        ),
    ]
