# Generated by Django 6.0.3 on 2026-06-24 05:42

import re

import master_data.models
from django.db import migrations, models


def normalize_existing_sku_codes(apps, schema_editor):
    """Uppercase and strip whitespace from existing sku_codes, skipping any
    row whose normalized value would collide with another row (sku_code is
    unique) so the migration can never raise an IntegrityError."""
    FinishedProductVariant = apps.get_model('master_data', 'FinishedProductVariant')
    qs = FinishedProductVariant.objects.exclude(sku_code__isnull=True).exclude(sku_code='')
    for variant in qs:
        normalized = re.sub(r'\s+', '', variant.sku_code).upper()
        if normalized == variant.sku_code:
            continue
        collision = (FinishedProductVariant.objects
                     .filter(sku_code=normalized)
                     .exclude(pk=variant.pk)
                     .exists())
        if collision:
            continue
        variant.sku_code = normalized
        variant.save(update_fields=['sku_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0034_unique_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproductvariant',
            name='sku_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[master_data.models.validate_variant_code]),
        ),
        migrations.RunPython(normalize_existing_sku_codes, migrations.RunPython.noop),
    ]
