# Generated by Django 6.0.3 on 2026-06-24 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0035_alter_finishedproductvariant_sku_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestParameterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField()),
                ('characteristic', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('test_method', models.CharField(blank=True, max_length=100)),
                ('specification', models.CharField(blank=True, max_length=200)),
                ('spec_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('spec_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_parameters', to='master_data.product')),
            ],
            options={
                'db_table': 'master_test_parameter_templates',
                'ordering': ['product', 'sr_no'],
                'unique_together': {('product', 'sr_no')},
            },
        ),
    ]
