# Generated by Django 6.0.3 on 2026-06-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0036_testparametertemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('default_method', models.CharField(blank=True, max_length=100)),
                ('default_unit', models.CharField(blank=True, max_length=50)),
                ('value_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('bounded', 'Bounded (e.g. "<2.5", "1b")')], default='numeric', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_test_parameters',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TestDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('template', models.CharField(default='layout_A', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_test_definitions',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='default_test',
            field=models.ForeignKey(blank=True, help_text="First Fill Test report format used for this product's PRD batches.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='master_data.testdefinition'),
        ),
        migrations.CreateModel(
            name='TestDefinitionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('spec_type', models.CharField(choices=[('Report', 'Report'), ('Min', 'Min'), ('Max', 'Max'), ('Range', 'Range')], default='Report', max_length=10)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_definitions', to='master_data.parameter')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='master_data.testdefinition')),
            ],
            options={
                'db_table': 'master_test_definition_parameters',
                'ordering': ['test', 'sort_order'],
                'unique_together': {('test', 'parameter')},
            },
        ),
        migrations.DeleteModel(
            name='TestParameterTemplate',
        ),
    ]
