# Generated by Django 6.0.3 on 2026-05-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_assemblyorder_add_conversion_fields'),
        ('master_data', '0029_unit_base_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('assembly_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lines', to='assembly.assemblyorder')),
                ('location', models.ForeignKey(blank=True, help_text='Override location; defaults to assembly destination_location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_material_lines', to='master_data.location')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_lines', to='master_data.rawmaterialandconsumable')),
            ],
            options={
                'db_table': 'assembly_material_lines',
                'ordering': ['material__name'],
            },
        ),
    ]
