# Generated by Django 6.0.3 on 2026-06-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_assemblyorder_add_assembly_line'),
        ('master_data', '0029_unit_base_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyorder',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_dest_orders', to='master_data.location'),
        ),
    ]
