# Generated by Django 6.0.3 on 2026-06-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0005_assemblyorder_destination_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('assembled', 'Assembled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
