# Generated by Django 6.0.3 on 2026-06-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0007_add_label_print_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssemblyMaterialLine',
        ),
    ]
