# Generated by Django 6.0.3 on 2026-05-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('industry', 'Industry'), ('dealer', 'Dealer'), ('no-type', 'Not Set')], default='no-type', max_length=20),
        ),
    ]
