# Generated by Django 6.0.3 on 2026-06-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customer_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('industry', 'Industry'), ('dealer', 'Dealer'), ('retail', 'Retail'), ('no-type', 'Not Set')], default='no-type', max_length=20),
        ),
    ]
